FROM almalinux:8
#It copies the files from local to docker image
ADD hello.txt /tmp/ 
#It directly download and extract the content from internet to our docker image
ADD https://raw.githubusercontent.com/vinodkumarpaleti/dockerfiles/master/README.MD /tmp/
#It will untar the content directly into the docker image
ADD sample-1.tar /tmp/
