FROM almalinux:8
#It copies the files from local to docker image
ADD hello.txt /tmp/ 
ADD https://raw.githubusercontent.com/vinodkumarpaleti/dockerfiles/master/README.MD /tmp/
#It directly download and extract the content from internet to our docker image